### ISSUE TITLE
Links with "&" can break formatting

### ISSUE THREAD

**Issue by Nickster258** [OpenRedstoneEngineers/ChattORE#4]
![image](https://github.com/OpenRedstoneEngineers/ChattORE/assets/3431308/5a47e7e5-11ff-4263-8e91-ce67d7eeb2d5)

The issue stems from parsing the `&` codes prior to parsing links. This will in theory break any with a  valid `&` code. Will require a rework of [the message parsing section](https://github.com/OpenRedstoneEngineers/ChattORE/blob/master/src/main/kotlin/Messaging.kt#L77).

Also, links with `&k` will likely cause a [permissions error](https://github.com/OpenRedstoneEngineers/ChattORE/blob/67c5f5f749ed32c9e8fc57e32716a73e26356d5f/src/main/kotlin/listener/ChatListener.kt#L94).

Potential fix could be splitting on URL regex matches, though that can get ugly.

**Comment by StackDoubleFlow** [comment]
Was this fixed in #6?
